### ISSUE TITLE
Milestone 4

### ISSUE THREAD

**Issue by riikacharya-code** [Vassar-Marketplace/marketplaceApp#4]
- [x] User can follow another user
- [x] User can create profile
- [x]  User can add a profile pic

**Comment by riikacharya-code** [comment]
Done
